name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "tap_rilla/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/ci.yml"
  push:
    branches:
      - main
      - v*
    paths:
      - "tap_rilla/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/ci.yml"
  merge_group:
  workflow_dispatch:
    inputs: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
      - run: |
          uv sync --only-group=typing
          uv run mypy tap_rilla tests
          uv run ty check tap_rilla tests
