name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "tap_rilla/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/ci.yml"
  push:
    branches:
      - main
      - v*
    paths:
      - "tap_rilla/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/ci.yml"
  merge_group:
  workflow_dispatch:
    inputs: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
      - run: |
          uv sync --only-group=typing
          uv run mypy tap_rilla tests
          uv run ty check tap_rilla tests
